// packages/ssonext-form/src/app/register-form/register-form.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {NgForm} from "@angular/forms";
import {SsonextApiService} from "../ssonext-api.service";

@Component({
  selector: 'sn-register-form',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class RegisterFormComponent implements OnInit {


  emailExists = false;
  loading = false;

  constructor(private ssonextApiService: SsonextApiService) {
  }

  ngOnInit(): void {
  }

  async register(registerForm: NgForm) {
    const formData: { [key: string]: string } = {}
    for (let controlName in registerForm.form.controls) {
      formData[controlName] = registerForm.form.controls[controlName].value
    }
    await this.ssonextApiService.register(formData)
    return false;
  }

  async checkEmail(email:string) {
    this.emailExists = (await this.ssonextApiService.checkEmail(email))!.exists
  }
}

<form #registerForm="ngForm">

  <label>Name</label>
  <input type="text" name="name" required #nameInput="ngModel" ngModel>
  <span *ngIf="nameInput.invalid && nameInput.dirty " class="error">Name is mandatory</span>

  <label>Surname</label>
  <input type="text" name="surname" #surnameInput="ngModel" ngModel required>
  <span *ngIf="surnameInput.invalid && surnameInput.dirty " class="error">Surname is mandatory</span>


  <label>E-mail</label>
  <input type="email" name="email" required #emailInput="ngModel" ngModel (blur)="checkEmail(emailInput.value)">
  <span *ngIf="emailInput.invalid && emailInput.dirty "
        class="error">E-mail is mandatory</span>
  <span *ngIf="emailExists" class="error">This e-mail already exists. Did you forget your password?</span>


  <label>Password</label>
  <input type="password" name="password" #passwordInput="ngModel" ngModel required
         pattern="^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$">
  <span class="error" *ngIf="passwordInput.invalid && passwordInput.dirty">Insert at least a number, a symbol and a capital letter</span>
  <span *ngIf="passwordInput.value && passwordInput.value.length < 8 && passwordInput.dirty"
        class="error">Password should have 8 characters</span>


  <div class="flex mt-4">

    <button (click)="registerForm.valid && register(registerForm)" class="bo-btn"
            [class.disabled]="loading || !registerForm.valid || emailExists"
            type="button">
      Sign-up
    </button>
    <bo-loading *ngIf="loading"></bo-loading>
  </div>

</form>

// packages/ssonext-frontend/src/components/register-form.svelte
<script lang="ts">
  import { loggable, mergeable } from '../shared/store.util';
  import { queryParams } from '../shared/url-params.service';
  import { createEventDispatcher } from 'svelte';
  import { useForm, validators, email, required, Hint } from 'svelte-use-form';
  import { emailExists, requestRegistration } from '../services/api.service';
  import { _if } from '../shared/if.svelte-action';
  import { pattern } from '../shared/pattern.validator';
  import { notifyOnError, showNotification } from './notification/notification.store';

  const dispatch = createEventDispatcher();

  const params = queryParams<{ tenant: string }>();

  const s = loggable(
    mergeable({
      name: '',
      surname: '',
      email: '',
      password: '',
      emailExists: false,
      loading: false
    })
  );
  const form = useForm();

  async function checkEmail() {
    $s.emailExists = false;
    const exists = await emailExists($s.email, params.tenant);
    $s.emailExists = exists.exists;
  }

  async function register() {
    $s.loading = true;
    await notifyOnError(async () => {
      return await requestRegistration($s, params.tenant);
    }, 'There was an error while registering. Please try later');
    $s.loading = false;
  }
</script>

<div class="register-form">
  <form use:form>
    <label>Name</label>
    <input type="text" name="name" use:validators={[required]} bind:value={$s.name} />
    <Hint for="name" on="required">
      <span class="form-error">Name is mandatory</span>
    </Hint>

    <label>Surname</label>
    <input
      type="text"
      name="surname"
      use:validators={[required]}
      bind:value={$s.surname} />
    <Hint for="surname" on="required">
      <span class="form-error">Surname is mandatory</span>
    </Hint>

    <label>E-mail</label>
    <input
      type="email"
      name="email"
      use:validators={[required, email]}
      on:blur={checkEmail}
      bind:value={$s.email} />
    <Hint for="email" on="required">
      <span class="form-error">E-mail is mandatory</span>
    </Hint>
    <Hint for="email" on="email">
      <span class="form-error">Please provide a valid e-mail</span>
    </Hint>
    <span class="form-error" use:_if={$s.emailExists}>
      This e-mail already exists. Did you forget your password?
    </span>

    <label>Password</label>
    <input
      type="password"
      name="password"
      bind:value={$s.password}
      use:validators={[
        required,
        pattern(/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/)
      ]} />

    <Hint for="password" on="pattern">
      <span class="form-error">
        Insert at least a number, a symbol and a capital letter (minimum 8 characters)
      </span>
    </Hint>

    <div class="mt-4 flex">
      <button
        on:click={register}
        class="bo-button"
        class:disabled={!$form.valid || $s.loading}
        type="button">
        Sign-up
      </button>
      <div class="bo-loading" use:_if={$s.loading} />
    </div>
  </form>
</div>

<style lang="scss">
  .register-form {
    @apply block;
  }
</style>
